import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { PeecApiClient } from "../api-client.js";
import { requireProjectId, dateSchema, filterSchema, validateDateRange, toolResult, toolError } from "../util.js";
import type { SearchQueryRow } from "../types.js";

const SEARCH_QUERIES_FILTER_FIELDS = ["model_id", "model_channel_id", "tag_id", "topic_id", "prompt_id", "chat_id"] as const;

/** Registers the search_queries tool for retrieving search queries generated by AI models. */
export function registerSearchQueriesTool(server: McpServer, client: PeecApiClient) {
  server.registerTool(
    "search_queries",
    {
      title: "Search Queries",
      description: "Get search queries that AI models generated when answering prompts. Returns the actual search queries models used to find information. Useful for understanding how AI models research topics. Without date filters, returns data across all available dates. Empty results may indicate the project has no query data for the given time range or filters.",
      inputSchema: {
        project_id: z.string().min(1).describe("Project ID (uses PEECAI_PROJECT_ID env if omitted). Call list_projects to find IDs.").optional(),
        start_date: dateSchema.describe("Start date (YYYY-MM-DD). Omit for no lower bound.").optional(),
        end_date: dateSchema.describe("End date (YYYY-MM-DD). Omit for no upper bound.").optional(),
        filters: filterSchema(SEARCH_QUERIES_FILTER_FIELDS).optional(),
        limit: z.number().min(1).max(10000).default(100).describe("Max results (1-10000, default: 100)"),
        offset: z.number().min(0).default(0).describe("Results to skip"),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false, openWorldHint: false },
    },
    async ({ project_id, start_date, end_date, filters, limit, offset }, extra) => {
      try {
        const dates = validateDateRange(start_date, end_date);
        const body: Record<string, unknown> = {
          project_id: requireProjectId(project_id),
        };
        if (dates.start_date) body.start_date = dates.start_date;
        if (dates.end_date) body.end_date = dates.end_date;
        if (filters) body.filters = filters;
        body.limit = limit;
        body.offset = offset;

        const data = await client.post<SearchQueryRow[]>("/queries/search", body, undefined, extra.signal);
        const rows = data.map((row) => ({
          prompt_id: row.prompt.id,
          chat_id: row.chat.id,
          model_id: row.model?.id ?? null,
          date: row.date,
          query_index: row.query.index,
          query_text: row.query.text,
        }));
        return toolResult({ _summary: `${rows.length} search queries returned`, rows });
      } catch (e) {
        return toolError(e);
      }
    }
  );
}
