import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { PeecApiClient } from "../api-client.js";
import { requireProjectId, dateSchema, filterSchema, validateDateRange, toolResult, toolError } from "../util.js";
import type { ShoppingQueryRow } from "../types.js";

const SHOPPING_QUERIES_FILTER_FIELDS = ["model_id", "tag_id", "topic_id", "prompt_id"] as const;

/** Registers the shopping_queries tool for retrieving shopping/product queries generated by AI models. */
export function registerShoppingQueriesTool(server: McpServer, client: PeecApiClient) {
  server.registerTool(
    "shopping_queries",
    {
      description: "Get shopping/product queries that AI models generated when answering prompts. Returns product-related queries with associated product names. Useful for understanding product recommendations by AI models. Without date filters, returns data across all available dates. Empty results may indicate the project has no query data for the given time range or filters.",
      inputSchema: {
        project_id: z.string().min(1).describe("Project ID (uses PEECAI_PROJECT_ID env if omitted). Call list_projects to find IDs.").optional(),
        start_date: dateSchema.describe("Start date (YYYY-MM-DD). Omit for no lower bound.").optional(),
        end_date: dateSchema.describe("End date (YYYY-MM-DD). Omit for no upper bound.").optional(),
        filters: filterSchema(SHOPPING_QUERIES_FILTER_FIELDS).optional(),
        limit: z.number().min(1).max(10000).default(100).describe("Max results (1-10000, default: 100)"),
        offset: z.number().min(0).default(0).describe("Results to skip"),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false, openWorldHint: false },
    },
    async ({ project_id, start_date, end_date, filters, limit, offset }) => {
      try {
        const dates = validateDateRange(start_date, end_date);
        const body: Record<string, unknown> = {
          project_id: requireProjectId(project_id),
        };
        if (dates.start_date) body.start_date = dates.start_date;
        if (dates.end_date) body.end_date = dates.end_date;
        if (filters) body.filters = filters;
        body.limit = limit;
        body.offset = offset;

        const data = await client.post<ShoppingQueryRow[]>("/queries/shopping", body);
        const rows = data.map((row) => ({
          prompt_id: row.prompt.id,
          chat_id: row.chat.id,
          model_id: row.model.id,
          date: row.date,
          query_text: row.query.text,
          query_products: row.query.products,
        }));
        return toolResult({ _summary: `${rows.length} shopping queries returned`, rows });
      } catch (e) {
        return toolError(e);
      }
    }
  );
}
